# Helix language settings

######## C

[[language]]
name = "c"
auto-format = true

######## C++

[[language]]
name = "cpp"
auto-format = true

######## Haskell
[[language]]
name = "haskell"
auto-format = true
formatter = { command = "ormolu", args = ["--stdin-input-file", "."] }

######## Nix

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

######## OCaml

[[language]]
name = "ocaml"
auto-format = true
formatter = { command = "ocamlformat", args = [] }

######## Rust

[[language]]
name = "rust"
auto-format = true

######## Toml

[[language]]
name = "toml"
auto-format = true
