# Helix language settings

######## C

[[language]]
name = "c"
auto-format = true

######## Nix

[[language]]
name = "nix"
auto-format = true

######## Python

[[language]]
name = "python"
config = { pylsp.plugins.pylint.enabled = true }

######## Rust

[[language]]
name = "rust"
auto-format = true

######## Toml

[[language]]
name = "toml"
auto-format = true
